# Generated by Django 5.1.6 on 2025-02-19 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_tag_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=models.ImageField(upload_to='courses/%Y/%m'),
        ),
    ]
